app/models.py
from __future__ import annotations

from dataclasses import dataclass
from time import time
from typing import Any

from app import redis


@dataclass
class Link:
    name: str
    description: str
    url: str
    created_date: int = int(time())
    modified_date: int = int(time())
    id: int = 0

    @staticmethod
    def get_links() -> list[dict[str, Any]]:
        link_ids = redis.zrange("links", 0, -1)
        links = []

        # get all data based on ids in reverse order
        for link_id in link_ids:
            link = redis.hgetall(f"link:{link_id}")
            links.append(link)

        return links

    @staticmethod
    def get_one_link(id: str) -> dict[str, Any]:
        return redis.hgetall(f"link:{id}")

    @staticmethod
    def create_link(new_link: Link) -> Link:
        redis_pipeline = redis.pipeline()
        redis_pipeline.multi()

        # prepare link id to be stored in redis
        next_link_id = redis.incr("link_id")
        new_link.id = next_link_id

        redis_pipeline.hset(f"link:{next_link_id}", mapping=vars(new_link))
        redis_pipeline.zadd("links", {next_link_id: new_link.created_date})
        redis_pipeline.execute()

        return new_link

    @staticmethod
    def update_link(new_data: Link, id: str) -> Link:
        redis_pipeline = redis.pipeline()
        redis_pipeline.multi()

        # update one data
        redis_pipeline.hset(f"link:{id}", mapping=vars(new_data))
        redis_pipeline.execute()

        return new_data

    @staticmethod
    def delete_link(id: str) -> None:
        redis_pipeline = redis.pipeline()
        redis_pipeline.multi()

        # delete one data
        redis_pipeline.delete(f"link:{id}")
        redis_pipeline.zrem("links", id)
        redis_pipeline.execute()

app/__init__.py
from flask import Flask
from redis import StrictRedis

from app.config import REDIS_HOST, REDIS_PASSWORD, REDIS_PORT, Config
from app.extensions import cors, limiter, talisman

# Initialize global database object.
redis = StrictRedis(
    host=REDIS_HOST, port=REDIS_PORT, password=REDIS_PASSWORD, decode_responses=True
)


def create_app(config_class=Config):
    # Initialize application.
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Setup Content Security Policy.
    csp = {
        "default-src": "'self'",
        "font-src": ["'self'", "fonts.googleapis.com", "fonts.gstatic.com"],
        "style-src-elem": ["'self'", "fonts.googleapis.com"],
    }

    # Setup global third-party middlewares with application factories.
    cors.init_app(app)
    limiter.init_app(app)
    talisman.init_app(app, content_security_policy=csp, force_https=False)

    with app.app_context():
        # Create components with our blueprints.
        from app.errors import errors_blueprint
        from app.links import links_blueprint
        from app.utils import utils_blueprint
        from app.views import views_blueprint

        # Register our blueprints.
        app.register_blueprint(links_blueprint, url_prefix="/api/v1/links")
        app.register_blueprint(utils_blueprint, url_prefix="/api/v1/")
        app.register_blueprint(views_blueprint)

        # Register our global error handling blueprint.
        app.register_blueprint(errors_blueprint)

    return app

app/links/__init__.py
from operator import itemgetter
from re import IGNORECASE, compile, match

from flask import Blueprint, abort, jsonify, request

from app.models import Link

links_blueprint = Blueprint("links_blueprint", __name__)


def request_valid(request_body):
    required_keys = {"name", "description", "url"}
    name, description, url = itemgetter("name", "description", "url")(request_body)

    if not name or not description or not url:
        return False

    if all(key in request_body for key in required_keys):
        return True

    return False


def url_valid(url):
    regex = compile(
        r"^(?:http|ftp)s?://"  # http:// or https://
        r"(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|"  # domain...
        r"localhost|"  # localhost...
        r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"  # ...or ip
        r"(?::\d+)?"  # optional port
        r"(?:/?|[/?]\S+)$",
        IGNORECASE,
    )

    if not match(regex, url):
        return False

    return True


@links_blueprint.route("/", methods=["POST"])
def create_one_link():
    if not request_valid(request.json):
        abort(400, "You have inserted an invalid or empty input!")

    if not url_valid(request.json.get("url")):
        abort(400, "You have inserted an invalid URL!")

    # instantly map dictionary keys to class attributes
    new_link = Link.create_link(Link(**request.json))

    return jsonify(status="success", data=vars(new_link)), 201


@links_blueprint.route("/<id>", methods=["PATCH"])
def update_one_link(id):
    previous_link = Link.get_one_link(id)

    if not request_valid(request.json):
        abort(400, "You have inserted an invalid or empty input!")

    if not previous_link:
        abort(400, "There is no data with that identifier!")

    if not url_valid(request.json.get("url")):
        abort(400, "You have inserted an invalid URL!")

    # destructuring, python way
    name, description, url = itemgetter("name", "description", "url")(request.json)

    # manually create dictionary for updating link
    update_link = {
        "name": name,
        "description": description,
        "url": url,
        "created_date": previous_link.get("created_date"),
        "id": id,
    }

    # update link
    updated_link = Link.update_link(Link(**update_link), id)

    return jsonify(status="success", data=vars(updated_link)), 200


@links_blueprint.route("/<id>", methods=["DELETE"])
def delete_one_link(id):
    previous_link = Link.get_one_link(id)

    if not previous_link:
        abort(400, "There is no data with that identifier!")

    # delete link
    Link.delete_link(id)

    # return 204 no content
    return "", 204

app/utils/__init__.py
from flask import Blueprint, jsonify

utils_blueprint = Blueprint("utils_blueprint", __name__)


@utils_blueprint.route("/", methods=["GET"])
def connection_test():
    return jsonify(status="success", message="Connected successfully!"), 200


@utils_blueprint.route("/developer", methods=["GET"])
def developer_details():
    developer = {
        "name": "@lauslim12",
        "email": "nicholasdwiarto@yahoo.com",
        "github": "https://github.com/lauslim12",
        "linkedin": "https://www.linkedin.com/in/nicholasdwiarto/",
        "stackoverflow": "https://stackoverflow.com/users/13980107/nicholas-d",
        "website": "https://wwww.nicholasdw.com/",
    }

    return jsonify(status="success", data=developer), 200

app/views/__init__.py
from flask import Blueprint, abort, render_template

from app.models import Link

views_blueprint = Blueprint("views_blueprint", __name__)


@views_blueprint.route("/", methods=["GET"])
def home():
    links = Link.get_links()
    return render_template("home.html", title="Homepage", links=links), 200


@views_blueprint.route("/new", methods=["GET"])
def new():
    return render_template("new.html", title="New"), 200


@views_blueprint.route("/edit/<id>", methods=["GET"])
def edit(id):
    link_to_edit = Link.get_one_link(id)

    if not link_to_edit:
        abort(404)

    return render_template("edit.html", title="Edit", link=link_to_edit), 200

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#8f94fb" />
    <meta name="msapplication-navbutton-color" content="#8f94fb" />
    <meta name="apple-mobile-web-app-status-bar-style" content="#8f94fb" />

    <title>Home Dashboard &mdash; {{ title }}</title>

    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/png" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
  </head>
  <body>
    <header class="header">
      {% include "header.html" %}
    </header>

    <main class="content">
      {% block content %}
      {% endblock content %}
    </main>

    <footer class="footer">
      {% include "footer.html" %}
    </footer>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
  </body>
</html>

app/templates/edit.html
{% extends "base.html" %}

{% block content %}
  <section class="section-new">
    <form class="form">
      <div class="section-new__greetings">
        <h1 class="newdata-message">Edit Data</h1>
        <h2 class="newdata-sub">
          Please fill out this form to edit the link to be processed in this IoT Dashboard!
        </h2>
        <h3 class="newdata-tertiary">
          Click here to go
          <a href="{{ url_for('views_blueprint.home') }}"
            class="link-text"
            rel="noopener noreferrer"
          >
            back!
          </a>
        </h3>
      </div>

      <div class="form__holder">
        <label for="link_name" class="form__holder__label">Link Name</label>
        <input id="link_id"
          name="link_id"
          type="hidden"
          value="{{ link.id }}"
          autocomplete="off"
          readonly
          required
        />

        <input id="link_name"
          class="form__holder__input"
          name="link_name"
          type="text"
          placeholder="GitHub"
          value="{{ link.name }}"
          autocomplete="off"
          required
        />
        <p class="form__holder__description">
          Name of the website that you are going to save.
        </p>
      </div>

      <div class="form__holder">
        <label for="link_description" class="form__holder__label">Link Description</label>
        <input id="link_description"
          class="form__holder__input"
          name="link_description"
          type="text"
          placeholder="Place for me to store my code"
          value="{{ link.description }}"
          autocomplete="off"
          required 
        />
        <p class="form__holder__description">
          Description of your link/website.
        </p>
      </div>

      <div class="form__holder">
        <label for="link_url" class="form__holder__label">Link URL</label>
        <input id="link_url"
          class="form__holder__input"
          name="link_url""
          type="text"
          placeholder="https://github.com/"
          value="{{ link.url }}"
          autocomplete="off"
          required
        />
        <p class="form__holder__description">
          The URL of your link.
        </p>
      </div>

      <div class="form__holder__submit">
        <button id="button-edit-submit" class="button" type="submit">Edit</button>
      </div>
    </form>
  </section>
{% endblock %}

app/templates/footer.html
<p>Developed by Nicholas Dwiarto W.
  <a class="link-text" 
    href="https://github.com/lauslim12" 
    target="_blank" 
    rel="noopener noreferrer"
  >
    (@lauslim12)
  </a>
</p>

app/templates/header.html
<div class="header__link">
  <a class="link-text" href="{{ url_for('views_blueprint.home') }}" rel="noopener noreferrer">Home</a>
</div>

<div class="header__link">
  <a class="link-text header__link" href="{{ url_for('views_blueprint.new') }}" rel="noopener noreferrer">New</a>
</div>

app/templates/home.html
{% extends "base.html" %}

{% macro card(link="") %}
  <div class="dashboard__grid-item">
    <h5 class="dashboard__grid-item__title">{{ link.name }}</h5>

    <p class="dashboard__grid-item__desc">
      {{ link.description }}
    </p>

    <div class="spacer"></div>

    <div class="dashboard__grid-item__actions">
      <div class="dashboard__grid-item__actions-left">
        <a class="link-text" target="_blank" href="{{ link.url }}" rel="noopener noreferrer">
          Visit
        </a>
      </div>

      <div class="dashboard__grid-item__actions-right">
        <a class="link-text" href="{{ url_for('views_blueprint.edit', id=link.id) }}" rel="noopener noreferrer">
          Edit
        </a>
        <a
          class="button--delete link-text"
          href="#"
          rel="noopener noreferrer"
          data-linkid="{{ link.id }}"
        >
          Delete
        </a>
      </div>
    </div>
  </div>
{% endmacro %}

{% block content %}
  <section class="section-main">
    <div class="section-main__greetings">
      <h1 class="welcome-message">
        Welcome back, <span class="name-color">friend!</span>
      </h1>
      <h2 class="welcome-message-sub">Raspberry Pi is ready!</h2>
      <h3 class="welcome-message-tertiary">Hope you had a great day.</h3>
    </div>

    <div class="dashboard">
      <h4 class="welcome-message-quartnernary">Check out your links that you added to your dashboard:</h4>
      {% if links %}
        <div class="dashboard__grid">
          {% for link in links %}
            {{ card(link) }}
          {% endfor %}
        </div>
      {% else %}
        <p class="no-data-message">You have no data inserted yet! Maybe add something new?</p>
      {% endif %}
    </div>
  </section>
{% endblock %}

app/templates/new.html
{% extends "base.html" %}

{% block content %}
  <section class="section-new">
    <form class="form">
      <div class="section-new__greetings">
        <h1 class="newdata-message">New Data</h1>
        <h2 class="newdata-sub">
          Please fill out this form for your new link to be processed in this IoT Dashboard!
        </h2>
        <h3 class="newdata-tertiary">
          Click here to go
          <a href="{{ url_for('views_blueprint.home') }}"
            class="link-text"
            rel="noopener noreferrer"
          >
            back!
          </a>
        </h3>
      </div>

      <div class="form__holder">
        <label for="link_name" class="form__holder__label">Link Name</label>
        <input id="link_name"
          class="form__holder__input"
          name="link_name"
          type="text"
          placeholder="GitHub"
          autocomplete="off"
          required
        />
        <p class="form__holder__description">
          Name of the website that you are going to save.
        </p>
      </div>

      <div class="form__holder">
        <label for="link_description" class="form__holder__label">Link Description</label>
        <input id="link_description"
          class="form__holder__input"
          name="link_description"
          type="text"
          placeholder="Place for me to store my code"
          autocomplete="off"
          required
        />
        <p class="form__holder__description">
          Description of your link/website.
        </p>
      </div>

      <div class="form__holder">
        <label for="link_url" class="form__holder__label">Link URL</label>
        <input id="link_url"
          class="form__holder__input"
          name="link_url""
          type="text"
          placeholder="https://github.com/"
          autocomplete="off"
          required 
        />
        <p class="form__holder__description">
          The URL of your link. Must be in the right format: https://google.com for example.
        </p>
      </div>

      <div class="form__holder__submit">
        <button id="button-new-submit" class="button" type="submit">Submit</button>
      </div>
    </form>
  </section>
{% endblock %}